# fly.toml file generated for helloabc on 2023-04-07T10:40:34+08:00

app = "helloabc"
kill_signal = "SIGINT"
kill_timeout = 5
primary_region = "nrt"

[[services]]
  protocol = "tcp"
  internal_port = 5000
  processes = ["app"]

  [[services.ports]]
    port = 80
    handlers = ["http"]
    force_https = true

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]
  [services.concurrency]
    type = "connections"
    hard_limit = 25
    soft_limit = 20